### ISSUE TITLE
Anwendung synchronisiert Daten mit Server

### ISSUE THREAD

**Issue by npfeiler1** [TGM-HIT/syt5-gek1051-mobile-application-jamp#17]
Als Benutzer muss es möglich sein, dass die Anwendung meine Daten laufend mit dem Server synchronisiert, damit andere Benutzer meine Änderungen sehen können.

**Comment by NatiMirauta7** [comment]
Couch DB aufgesetzt Möglichkeiten gefunden Couch DB zu konfigurieren (local.ini, /_utils)
