### ISSUE TITLE
Implementierung Suchleiste

### ISSUE THREAD

**Issue by npfeiler1** [TGM-HIT/syt5-gek1051-mobile-application-jamp#18]
Als Benutzer erwarte ich die Implementierung einer Suchleiste, mit der ich hinzugefügte Artikel einfach finden kann.

**Comment by yakalin** [comment]
Ich habe eine benutzerfreundliche Suchleiste implementiert, mit der man die Items aller Listen durchsuchen kann. Beim Finden eines Items wird die jeweilige Liste geöffnet. Beim Klicken des X Buttons wird die vorher geöffnete Liste wieder geschlossen. ~ @npfeiler1
