### ISSUE TITLE
Server Synchronisierung - Deploying

### ISSUE THREAD

**Issue by npfeiler1** [TGM-HIT/syt5-gek1051-mobile-application-jamp#19]
Als Benutzer erwarte ich, dass jegliche Änderungen von anderen Benutzern stets mit meiner Anwendung synchronisiert sind, damit Differenzen oder Synchronisierungsverzögerungen vermieden werden.

**Comment by yakalin** [comment]
Mit dem couchdb von @NatiMirauta7 konnte ich vorerst eine Synchronisation mit der lokal laufenden App herstellen, anschließend habe ich auf AWS eine couchdb erstellt und diese auf SSL konfiguriert, damit funktioniert es jetzt auch in der live app. Ich würde damit den Issue schließen 😄.
