### ISSUE TITLE
Erhalt eines "Log-In Links"

### ISSUE THREAD

**Issue by npfeiler1** [TGM-HIT/syt5-gek1051-mobile-application-jamp#20]
Als Benutzer erwarte ich den Erhalt eines Link, mit dem ich sofort auf den Dienst zugreifen kann, damit eine Registrierung aus Komfortgründen entgangen wird.

**Comment by tjanits** [comment]
Nach dem Ersten Versuch jedem User eine der vordefinierten IDs aus dem .env File zuzuweisen sind wir zu dem Schluss gekommen, dass der Zeitliche Aufwand dieser Implementation zu hoch wäre und haben das Konzept geändert. In der Finalen Variante bekommt der User jetzt den Link beim Aufruf der Anwendung und kann mithilfe dessen auf die Shoppinliste zugreifen.
