### ISSUE TITLE
Löschen von Elementen

### ISSUE THREAD

**Issue by npfeiler1** [TGM-HIT/syt5-gek1051-mobile-application-jamp#23]
Als Benutzer erwarte ich, dass das "Löschen" von Artikeln oder Listen keine wirkliche Entfernung darstellt, sondern diese nur Versteckt, um die Konsistenz zu bewahren.

**Comment by yakalin** [comment]
Es ist automatisch der Fall, deswegen erledigt. Juhuuu 😀
