### ISSUE TITLE
Supermarkt-Auswahl für Standort anpassen

### ISSUE THREAD

**Issue by npfeiler1** [TGM-HIT/syt5-gek1051-mobile-application-jamp#27]
Als Benutzer erwarte ich beim Angeben des Namens einer Supermarkt-Kette, die nächstgelegenen Filialen dieser Kette angezeigt zu bekommen, um den geplanten Ort meines Einkaufs zu notieren.

**Comment by npfeiler1** [comment]
- [ ] API-Abfragefunktion implementieren
- [ ] Datenaufbereitung und -rückgabe
- [ ] Eingabefeld für Supermarktnamen
- [ ] Standortabfrage implementieren
- [ ] Anzeige der Suchergebnisse
- [ ] Testing
- [ ] Dokumentierung

**Comment by yakalin** [comment]
works 👍
